services:
  mysql:
    image: mysql:8.4.1
    container_name: mysql-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./volumes/conf:/etc/mysql/conf.d
    networks:
      - my-network

networks:
  my-network:
    name: my-custom-network
    driver: bridge
