name: CD

on:
  push:
    branches: ["main"]
  workflow_dispatch: # 수동 실행 가능

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 - Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            tmux kill-session -t deploy_session || true
            sleep 2
            tmux new-session -d -s deploy_session || { echo "❌ tmux 세션 생성 실패"; exit 1; }
            sleep 2  # tmux 세션 안정화 대기

            # Backend 작업
            tmux send-keys "cd NBE4-5-2-Team04" C-m
            tmux send-keys "git pull origin main" C-m
            tmux send-keys "cd backend" C-m
            tmux send-keys "./gradlew build -x test -Dorg.gradle.jvmargs=\"-Xmx256m\"" C-m

            # Spring 애플리케이션을 백그라운드에서 실행
            tmux send-keys "java -Xms64m -Xmx128m -jar build/libs/project2-0.0.1-SNAPSHOT.jar &" C-m

            # Spring 애플리케이션 실행 후 30초 대기
            sleep 30  # 이 부분에서 30초 대기

            # 새로운 tmux 창에서 frontend 작업 시작
            tmux new-window -t deploy_session:1 -n 'frontend'  # 새로운 창에서 frontend 작업 시작
            tmux send-keys "cd NBE4-5-2-Team04" C-m
            tmux send-keys "cd frontend" C-m
            tmux send-keys "npm install" C-m
            tmux send-keys "npm run build && npm start" C-m

            # tmux 세션에 연결
            tmux attach -t deploy_session
