name: local CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      SPRING_PROFILES_ACTIVE: test
      USE_MYSQL: true
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for Gradle
        run: chmod +x backend/gradlew

      - name: Set up MySQL
        if: env.USE_MYSQL == 'true'
        uses: mirromutth/mysql-action@v1.1
        with:
          host_port: 3306
          container_port: 3306
          character_set_server: "utf8mb4"
          collation_server: "utf8mb4_general_ci"
          mysql_version: "8.0"
          mysql_database: "Pathy"
          mysql_user: ${{ secrets.MYSQL_USERNAME }}
          mysql_password: ${{ secrets.MYSQL_PASSWORD }}
          mysql_root_password: ${{ secrets.MYSQL_PASSWORD }}

      - name: Wait for MySQL
        if: env.USE_MYSQL == 'true'
        run: |
          echo "Waiting for MySQL to be ready..."
          until mysql --protocol=TCP -h127.0.0.1 -u${{ secrets.MYSQL_USERNAME }} -p${{ secrets.MYSQL_PASSWORD }} -e "SELECT 1"; do
            sleep 1
          done

      - name: Build and Test
        working-directory: ./backend
        run: ./gradlew build --no-daemon
