name: local CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      SPRING_PROFILES_ACTIVE: test
      USE_MYSQL: true
      MYSQL_HOST: host.docker.internal
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for Gradle
        run: chmod +x backend/gradlew

      # ✅ 기존 MySQL 컨테이너 제거 후 다시 실행
      - name: Start MySQL Container
        if: env.USE_MYSQL == 'true'
        run: |
          docker rm -f mysql-container || true
          docker run -d --name mysql-container \
            -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
            -e MYSQL_USER=${{ secrets.MYSQL_USERNAME }} \
            -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
            -e MYSQL_DATABASE=Pathy \
            -p 3306:3306 \
            --add-host=host.docker.internal:host-gateway \
            mysql:8.4.1

      # ✅ MySQL 실행 상태 확인
      - name: Check MySQL Container Status
        if: env.USE_MYSQL == 'true'
        run: |
          echo "Checking running containers..."
          docker ps -a
          echo "Checking MySQL logs..."
          docker logs mysql-container || true

      # ✅ MySQL이 완전히 실행될 때까지 대기
      - name: Wait for MySQL
        if: env.USE_MYSQL == 'true'
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if mysql --protocol=TCP -h $MYSQL_HOST -u${{ secrets.MYSQL_USERNAME }} -p${{ secrets.MYSQL_PASSWORD }} -e "SELECT 1"; then
              echo "MySQL is ready!"
              exit 0
            fi
            echo "Waiting..."
            sleep 2
          done
          echo "MySQL did not start in time."
          exit 1

      # ✅ Gradle 빌드 및 테스트 실행
      - name: Build and Test
        working-directory: ./backend
        run: ./gradlew build --no-daemon
