name: local CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      SPRING_PROFILES_ACTIVE: test
      USE_MYSQL: true
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for Gradle
        run: chmod +x backend/gradlew

      - name: Set up MySQL
        if: ${{ env.USE_MYSQL == 'true' }}
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: "utf8mb4"
          collation server: "utf8mb4_general_ci"
          mysql version: "8.4"
          mysql database: "Pathy"
          mysql user: ${{ secrets.MYSQL_USERNAME }}
          mysql password: ${{ secrets.MYSQL_PASSWORD }}
          mysql root password: ${{ secrets.MYSQL_PASSWORD }}
          mysql additional args: "--default-authentication-plugin=mysql_native_password"

      - name: Set MySQL ENV Vars
        run: |
          echo "MYSQL_URL=jdbc:mysql://localhost:3306/Pathy?serverTimezone=Asia/Seoul&useSSL=false" >> $GITHUB_ENV
          echo "MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}" >> $GITHUB_ENV
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> $GITHUB_ENV

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            nc -zv 127.0.0.1 3306 && echo "MySQL is up" && exit 0
            echo "Waiting for MySQL..."
            sleep 2
          done
          echo "MySQL failed to start" && exit 1

      - name: Build and Test
        working-directory: ./backend
        run: ./gradlew build --no-daemon
