name: local CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      SPRING_PROFILES_ACTIVE: test
      USE_MYSQL: false # 기본적으로 H2 사용, MySQL 사용하려면 true로 변경
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }} # GitHub Secrets에서 환경 변수 주입

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for Gradle
        run: chmod +x backend/gradlew

      # MySQL 설정 (기본적으로 비활성화)
      - name: Set up MySQL
        if: env.USE_MYSQL == 'true' # USE_MYSQL이 true이면 MySQL 실행
        uses: mirromutth/mysql-action@v1.1
        with:
          host-port: 3306
          container-port: 3306
          character-set-server: "utf8mb4"
          collation-server: "utf8mb4_general_ci"
          mysql-version: "8.0"
          mysql-database: "project2_team4"
          mysql-root-password: 1234

      - name: Wait for MySQL
        if: env.USE_MYSQL == 'true' # USE_MYSQL이 true이면 실행
        run: |
          echo "Waiting for MySQL to be ready..."
          until mysql -h127.0.0.1 -uroot -p1234 -e "SELECT 1"; do
            sleep 1
          done

      - name: Build and Test
        working-directory: ./backend
        run: ./gradlew build --no-daemon
