name: local CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      SPRING_PROFILES_ACTIVE: test
      USE_MYSQL: true
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for Gradle
        run: chmod +x backend/gradlew

      - name: Start MySQL Container
        if: env.USE_MYSQL == 'true'
        run: |
          docker run -d --name mysql-container \
            -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
            -e MYSQL_USER=${{ secrets.MYSQL_USERNAME }} \
            -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
            -e MYSQL_DATABASE=Pathy \
            -p 3306:3306 \
            --health-cmd="mysqladmin ping -h localhost" \
            --health-interval=10s --health-timeout=5s --health-retries=5 \
            mysql:8.0

      - name: Check MySQL Logs
        if: env.USE_MYSQL == 'true'
        run: |
          docker ps -a
          docker logs $(docker ps -aqf "ancestor=mysql:8.0")

      - name: Wait for MySQL
        if: env.USE_MYSQL == 'true'
        run: |
          echo "Checking MySQL connection..."
          until mysql --protocol=TCP -h127.0.0.1 -u${{ secrets.MYSQL_USERNAME }} -p${{ secrets.MYSQL_PASSWORD }} -e "SELECT 1" || \
                mysql --protocol=TCP -hlocalhost -u${{ secrets.MYSQL_USERNAME }} -p${{ secrets.MYSQL_PASSWORD }} -e "SELECT 1"; do
            echo "Waiting for MySQL to be ready..."
            sleep 2
          done
          echo "MySQL is ready!"

      - name: Build and Test
        working-directory: ./backend
        run: ./gradlew build --no-daemon
